/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_OPPORTUNITY: 'add-opportunity',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sigin-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  FORGOT_PASSWORD: 'forgot-password',
  VOLUNTEER_SIGNUP: 'volunteer-signup',
  ABOUT_US: 'about-us',
  ORGANIZATION_LIB: 'organization_library',
  ORGANIZATION_SIGNUP: 'organization-signup',
  VOLUNTEER_PROFILE: 'volunteer-profile',
  LIST_EVENTS: 'browse-opportunities',
  EDIT_VOLUNTEER_PROFILE: 'edit-volunteer-profile',
  GOOGLE_MAP: 'google-map',
  ORGANIZATION_PROFILE: 'organization-profile',
  SEND_EMAIL_TO_ORG: 'send-email-to-org',
  LIST_VOLUNTEER_AT_EVENT: 'list-volunteer-at-event',
  TERMS_AND_CONDITIONS: 'terms-and-conditions',
};
