/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_OPPORTUNITY: 'add-opportunity',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  VOLUNTEER_SIGNUP: 'volunteer-signup',
  ABOUT_US: 'about-us',
  ORGANIZATION_LIB: 'organization_library',
  ORGANIZATION_SIGNUP: 'organization-signup',
  VOLUNTEER_PROFILE: 'volunteer-profile',
  LIST_EVENTS: 'browse-opportunities',
  EDIT_VOLUNTEER_PROFILE: 'edit-volunteer-profile',
};
